### ISSUE TITLE
NSMBe5 has stopped working

### ISSUE THREAD

**Issue by abkhur** [Treeki/NewerSMBW#3]
So, I got NSMBe5 a little while back and now for some odd reason, it doesn't open. Whenever i try opening it, a popup appears saying "NSMBe5 has stopped working, we're sending crash details to Microsoft". I kept deleting and re-downloading NSMBe5 but the same thing happened. I then proceeded to restart my pc and the same outcome came. I have no clue what to do. Please help.

**Comment by abkhur** [comment]
wrong place

**Comment by Kysonati** [comment]
Idk bro have you tried resetting your internet router? If so, maybe a fresh windows 10 install will help? As a last resort, try deleting System 32, it might have something that crashes your program
